apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ml-service
  labels:
    app: {{ .Release.Name }}-ml-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-ml-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
